# Generated by Django 4.1.3 on 2022-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirmpassword', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='login_tb',
            new_name='signin_tb',
        ),
        migrations.DeleteModel(
            name='contact_tb',
        ),
    ]
