# Generated by Django 4.1.3 on 2022-11-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_cont_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('offprice', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('proimage', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.DeleteModel(
            name='signin_tb',
        ),
        migrations.RemoveField(
            model_name='signup_tb',
            name='confirmpassword',
        ),
    ]
