# Generated by Django 4.1.3 on 2022-11-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0010_order_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_tb',
        ),
    ]
