# Generated by Django 4.1.3 on 2022-11-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0011_delete_order_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_tb',
            name='hashpassword',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
